[package]
name = "mem-skel"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
rhdl = {git = "https://github.com/samitbasu/rhdl.git",rev = "8d04954"}
rhdl-fpga = {git = "https://github.com/samitbasu/rhdl.git",rev = "8d04954"}
